---
- hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        update_cache: yes
        state: present
    - name: Start Docker
      systemd:
        name: docker
        state: started
        enabled: yes